# basic stuff
bind r source-file ~/.config/tmux/tmux.conf
set -g mouse on
set -g mode-keys vi
set-option -g allow-rename off

# remap prefix to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# remap split panes to | and -
bind '\' split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes with Alt-vimarrow
bind -n M-l select-pane -R
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U

##############
# APPEARANCE #
##############

# disable bell
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# modes
setw -g clock-mode-colour white
setw -g mode-style "fg=black bg=white bold"

# panes
set -g pane-border-style "fg=white"
set -g pane-active-border-style "fg=blue"

# status bar
set -g status-position bottom
set -g status-justify left
set -g status-style "fg=blue"

set -g status-left ''
set -g status-left-length 10

set -g status-right-style "fg=blue"
set -g status-right "%H:%M %d-%m-%Y "
set -g status-right-length 50

setw -g window-status-current-style "fg=blue"
setw -g window-status-current-format " #I #W #F "

setw -g window-status-style "fg=white"
setw -g window-status-format " #I #W #F "

setw -g window-status-bell-style "fg=white bold"

# messages
set -g message-style "fg=white bg=blue bold"
